### ISSUE TITLE
cannot run file in version 3 on esp8266

### ISSUE THREAD

**Issue by wohltat** [BIPES/BIPES#134]
I'm not able to run the following program:

``` python
from machine import Pin

def gpio_set(pin,value):
  if value >= 1:
    Pin(pin, Pin.OUT).on()
  else:
    Pin(pin, Pin.OUT).off()


gpio_set((2), False)

#Code automatically generated by BIPES (http://www.bipes.net.br)
#Author: 'Xian'
#IOT ID: 0
#Description: 'Blinkytest'
```

![image](https://user-images.githubusercontent.com/4751351/174490301-9f324a40-277d-4556-bf18-e0ce1d8f6e4b.png)

When i press the run / play button then in the console the following error is shown
```
>>> 
paste mode; Ctrl-C to cancel, Ctrl-D to finish
=== from machine import Pindef gpio_set(pin,value):  if value >= 1:    Pin(pin, Pin.OUT).on()  else:    Pin(pin, Pin.OUT).off()gpio_set((2), False)#Code automatically generated by BIPES (http://www.bipes.net.br)#Author: 'Xian'#IOT ID: 0#Description: 'Blinkytest'
Traceback (most recent call last):
  File "<stdin>", line 1
SyntaxError: invalid syntax
>>> 
>>> 
```

I cannot select esp8266 but i don't think it has anything to do with this problem. It is detected though.

Btw, the connection is not reestablished automatically if lost. For example on a soft reset (ctrl + d) the connection has to be made manually again.

**Comment by gastmaier** [comment]
Hi, just made a series of commits fixing the issues.
I update the server, Ctrl+F5 in the browser to update and check you are at v3.0.10 by clicking the logo and checking the hidden footer.

![image](https://user-images.githubusercontent.com/2892061/174504469-e55666c0-5e4d-47a2-96eb-b65fdfa529f8.png)
