### ISSUE TITLE
LED Pin is not named as in previous version

### ISSUE THREAD

**Issue by wohltat** [BIPES/BIPES#139]
![image](https://user-images.githubusercontent.com/4751351/174536915-19edde29-a85b-4e2e-bfd6-dee298c1fc4a.png)

Version 3.0.10

in Version 2:
![image](https://user-images.githubusercontent.com/4751351/174537831-e36a441d-4b48-42e0-bcc3-9b4402d808e4.png)

**Comment by gastmaier** [comment]
Humm, the WemosD1 mini seems to have this pinout
![](http://blog.robberg.net/wp-content/uploads/2017/09/esp8266-wemos-d1-mini-pinout.png)
and the ESP8266
![](https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Ftse4.mm.bing.net%2Fth%3Fid%3DOIP.tW6qJrOJ2eys6JbSGoICqgHaGP%26pid%3DApi&f=1)
which matches what the third version is rendering for each device.

The file that sets the pinout is [static/page/device/devices.js](https://github.com/BIPES/BIPES/blob/third/static/page/device/devices.js)

**Comment by wohltat** [comment]
The pin mapping is fine. It's not about differences between ESP
This issue is just about that is harder to find the onboard LED pin for a beginner. 
Since pins are labeled with SCL, SCA, etc. it would be nice to have this for LED as well.

I can try to add it, but i have some issues with my git setup i need to solve.
