### ISSUE TITLE
cannot send commands or programs 

### ISSUE THREAD

**Issue by wohltat** [BIPES/BIPES#141]
since version 3.0.10 i cannot send anything via the console.
Sending the programs doesn't work as well.

I guess this is a fundamental problem with the device communication hence the device info issue #140.

Tested on two different computers.

**Comment by gastmaier** [comment]
Sorry about that,
I really messed up in commit d6a7789370ed3581ec0f01e80d3d218bcba94ce4.
I just fixed for v3.0.11, commit c3f3f9e691c353a671197b0e925fa0b2642c8375.
