### ISSUE TITLE
micropython version outdated

### ISSUE THREAD

**Issue by wohltat** [BIPES/BIPES#150]
The version that can be uploaded with the web installer is outdated (1.17). 
The current version is 1.19.1
https://micropython.org/download/esp8266/

> Firmware
> Releases
> [v1.19.1 (2022-06-18) .bin](https://micropython.org/resources/firmware/esp8266-20220618-v1.19.1.bin) [[.elf]](https://micropython.org/resources/firmware/esp8266-20220618-v1.19.1.elf) [[.map]](https://micropython.org/resources/firmware/esp8266-20220618-v1.19.1.map) [[Release notes]](https://github.com/micropython/micropython/releases/tag/v1.19.1) (latest)
> [v1.18 (2022-01-17) .bin](https://micropython.org/resources/firmware/esp8266-20220117-v1.18.bin) [[.elf]](https://micropython.org/resources/firmware/esp8266-20220117-v1.18.elf) [[.map]](https://micropython.org/resources/firmware/esp8266-20220117-v1.18.map) [[Release notes]](https://github.com/micropython/micropython/releases/tag/v1.18)
> [v1.17 (2021-09-02) .bin](https://micropython.org/resources/firmware/esp8266-20210902-v1.17.bin) [[.elf]](https://micropython.org/resources/firmware/esp8266-20210902-v1.17.elf) [[.map]](https://micropython.org/resources/firmware/esp8266-20210902-v1.17.map) [[Release notes]](https://github.com/micropython/micropython/releases/tag/v1.17)

**Comment by rafaelaroca** [comment]
Hello. Sorry for the delay @wohltat.

Here are some updated flasher files:

https://bipes.net.br/flash/esp-web-tools-2023/

https://bipes.net.br/flash/esp-web-tools1.22.2/ (2024)

best regards
Rafael
