### ISSUE TITLE
Raspberry Pi Pico W - LCD Library Missing

### ISSUE THREAD

**Issue by carlosgblos** [BIPES/BIPES#161]
When trying to use the LCD on Raspberry Pi Pico W, it shows a message as page not found at chrome console. 
Surely we can (and will) download the libraries and keep teaching my son, but would be amazing to have it fixed for educational purposes. 

thanks and amazing tool you built.

**Comment by jetannenbaum** [comment]
Hi Carlos,

   I recently added the LCD library for the Pico.  You can use the https://bipes.net.br/pico/ui/ site.  It is built specifically for the RP2040 microprocessors

   Jet
