### ISSUE TITLE
Servo position error invoking API - named parameter doesn't exist

### ISSUE THREAD

**Issue by freemansoft** [BIPES/BIPES#169]
MicroPython v1.19.1-782-g699477d12 on 2022-12-20; Raspberry Pi Pico W with RP2040

```
>>> 
paste mode; Ctrl-C to cancel, Ctrl-D to finish
=== from machine import PWM
=== from machine import Pin
=== 
=== 
=== pservo = Pin((0))
=== servo = PWM(pservo,freq=50)
=== servo.duty(90)
=== 
=== 
=== 
Traceback (most recent call last):
  File "<stdin>", line 6, in <module>
TypeError: function doesn't take keyword arguments
```

**Comment by jetannenbaum** [comment]
Hi Joe,

   There are a few "quirks" in the RP204 implementation of MicroPython.
Try this version of BIPES is optimized for the Pico, Pico W, and MakerPi
RP2040: https://bipes.net.br/pico/ui/

   Thanks,

     Jet

**Comment by freemansoft** [comment]
That version worked for the RP2040 with respect to servos.

**Comment by freemansoft** [comment]
This is fixed in the offline branch
