### ISSUE TITLE
Standardize on Visual Studio Code Typescript auto formatter

### ISSUE THREAD

**Issue by freemansoft** [BIPES/BIPES#171]
PRs would be easier if the javascript was formatted with a widely available auto formatter.  I'd recommend the Visual Studio Code Typescript formatter.  It has a selection to `enable/disable default Javascript Formatter`  Essentially enable the default javascript formatter.

**Comment by jetannenbaum** [comment]
Hi Joe,

   Not everyone is using VS Code when working in the repo.  Thanks for the
suggestion.  IMHO this should move to the discussion section, rather than
as an open issue.

   Thanks,

     Jet
