### ISSUE TITLE
Feature idea - Blocks Code tabs to store multiple programs open at the same time

### ISSUE THREAD

**Issue by ptal78** [BIPES/BIPES#27]
The idea came from a colleague. We would like to have multiple code examples open at the same time.

Pressing the program button loads the code of only one tab, that is currently displayed.

**Comment by ptal78** [comment]
My colleague also suggested it could be instead like a cabinet icon on the right side of the screen, so we can drag existing code into the cabinet storage, much like you might drag it into the bin. Then clicking on the bin, we get a graphical display of each code we placed in the cabinet.

**Comment by rafaelaroca** [comment]
Hi @ptal78  :-)

Does the new file manager created by @JorgeGMarques solve this issue?

![image](https://user-images.githubusercontent.com/31751413/131251884-b81ce05e-b233-4c5f-80d2-175a435220f1.png)

**Comment by JorgeGMarques** [comment]
It doesn't haha. It's about multiplex projects. I think you be a nice feature too.
Would use local storage to keep multiple project instead of only one.

**Comment by JorgeGMarques** [comment]
Work in progress.
Finally working  on it, it's already function but still need to fill all the possibility, like fetching the "legacy" single project, so no one would loose their work.

![image](https://user-images.githubusercontent.com/2892061/132963681-63fc60c3-1863-41fa-ba9d-4a6c39c65382.png)

**Comment by rafaelaroca** [comment]
Wow! Looking forward to use it. Great! :-)

**Comment by JorgeGMarques** [comment]
Done with 027de7d0d22a4ab80401ccfb28887a9b2689ab8e, e48b4c5e21672baef1371470a4da15460d876f44 and ce4971bed93b5b9df7714501dd24af110330bd83.
Shared projects are imported to the account panel and throws a notification.
