### ISSUE TITLE
No Download Library option for the Ultrasound sensor si Install option fails

### ISSUE THREAD

**Issue by ptal78** [BIPES/BIPES#40]
I can't get the Install HCSR04 ultrasound distance sensor installed through bipes as the download option is missing.

**Comment by rafaelaroca** [comment]
Hello, the files are really missing. Will fix it later today.

**Comment by rafaelaroca** [comment]
Solved. It is not needed to install the lib anymore. Just include the block and all the code will be generated. Tested on an ESP8266. Could you test on the ESP32? best regards!

**Comment by rafaelaroca** [comment]
Bug fixed and tested on ESP8266 with a HC - SR04
