### ISSUE TITLE
Loading Files on to the ESP32 is extremely slow

### ISSUE THREAD

**Issue by ptal78** [BIPES/BIPES#41]
Is there a reason each byte has to be written and then read individually?

This seems extremely slow.

**Comment by JorgeGMarques** [comment]
Worked on that in commit e3e8c8b0778b2ecb03697b78312f58547fe592ae with some others improvements in BIPES
However, it might be too fast now and I was losing some bytes with my ESP32, so I temporarily reduced the max packet size per sent chunk from 1000 to 500 bytes (`devinfo.json`) until I can test more the new algorithm.

Best regards

**Comment by rafaelaroca** [comment]
@JorgeGMarques fixed this issue recently. I tested and it works nicely.
