### ISSUE TITLE
Usage of deprecated "variableDB_" in generator_stub

### ISSUE THREAD

**Issue by casjengu** [BIPES/BIPES#47]
When implementing blocks, which use variableDB_ i get an increasing number of warnings in the Chrome DevTool Console.

The warning looks like this:
_variableDB\_ was deprecated on May 2021 and will be deleted on May 2026.
Use nameDB\_ instead._

Maybe you should consider changing the affected blocks accordingly. (variableDB_ was renamed to nameDB_ in May, 2021)
Source: [https://developers.google.cn/blockly/reference/js/global](https://developers.google.cn/blockly/reference/js/global)

**Comment by JorgeGMarques** [comment]
Thanks!
