### ISSUE TITLE
WebREPL not connecting over STA anymore

### ISSUE THREAD

**Issue by ptal78** [BIPES/BIPES#58]
I'm sure I had this working via my phone 5 or so weeks ago, but now WebREPL in Bipes isn't connecting to my ESP32.

I have a solid WiFi connection through my router as I can ping the ESP32 ip address without any problem.

After a successful connection, the ESP32 then runs the following code so it doesn't require any prompt:

import webrepl
webrepl.start(password='xxxx')

Any suggestions as to what I'm doing wrong please?

**Comment by ptal78** [comment]
It's okay. I worked it out. Wasn't using the ip address in the new position or the password.

Connects flawlessly!

**Comment by rafaelaroca** [comment]
Nice :-)
