### ISSUE TITLE
PWM deinit tool

### ISSUE THREAD

**Issue by ptal78** [BIPES/BIPES#60]
Hi,

It would be great if you could implement a PWM deinit block that allows the user to select from the existing PWM options.

I'm not sure how to do this in code to reference other existing blocks.

But the code is simple.

Eg.

pwm4.deinit()

Of course the user would someone need to select the pwm pin to deinitialize.

I don't have time to work on this though sorry.

Cheers

**Comment by JorgeGMarques** [comment]
Included with e59445c9948da88042a4d316a784d7e75523827d.

**Comment by ptal78** [comment]
Thanks. But it's not working yet because the number has been put in brackets as shown below, when it should be without brackets ie, pwm5.deinit() not pwm(5).deinit()

![image](https://user-images.githubusercontent.com/24988399/132158892-423c7544-654b-4fbd-bd1a-2eaecea91f5e.png)

**Comment by ptal78** [comment]
Also, as you can see from the code example, the gpio_set commands actually stop the pwm5 from working, as they redefine the pin. So it is quite important that the pwm5 = PWM(Pin(5)) line should be placed directly prior the pwm5.freq line.
