### ISSUE TITLE
PWM duty tool

### ISSUE THREAD

**Issue by ptal78** [BIPES/BIPES#62]
Can you possibly do a PWM duty tool to adjust the duty of the existing pwm? Possibly a pwm frquency tool might also come in handy.

To produce a code such as:

pwm4.duty(0)

**Comment by JorgeGMarques** [comment]
I will take a look at the [documentation ](https://docs.micropython.org/en/latest/esp8266/tutorial/pwm.html) to better implement these blocks later.

**Comment by ptal78** [comment]
Thanks.

The duty number can be any positive integer from 0 up.
The maximum doesn't matter.

Kind Regards,
Phil

**Comment by JorgeGMarques** [comment]
Done with 9eca7652503422529fdba7b09c8439c17684a830

**Comment by ptal78** [comment]
Thanks, but I can't seem to download and upload these new blocks.
