### ISSUE TITLE
Change By block in variables fails on ESP32 due to from numbers reference

### ISSUE THREAD

**Issue by ptal78** [BIPES/BIPES#65]
Change By block in variables fails due to the following line of code:

from numbers import Number

Please remove this line of code

**Comment by ptal78** [comment]
also, the number reference in the 2nd line should be int

that is, change:

time = (time if isinstance(time, Number) else 0) + 1

to:

time = (time if isinstance(time, int) else 0) + 1

**Comment by JorgeGMarques** [comment]
Solved with a02ccfc81f0de8cebcfaaf73bd73294cc919095d . I will include in the v0.2.3 release.
