### ISSUE TITLE
pwm and pico

### ISSUE THREAD

**Issue by timbuktuvariance** [BIPES/BIPES#66]
I am using a pico and going through some bipes blocks examples, LED blinking works great, but fading with PWM is giving an error (I have uploaded the [Raspberry pi code](https://projects.raspberrypi.org/en/projects/getting-started-with-the-pico/7) using the bipes console and it works fine). The error using the blocks from https://bipes.net.br/beta2/ui/#7piqwf  showing up on the console is:
`File "<stdin>", line 11, in <module>
AttributeError: 'PWM' object has no attribute 'duty'`

**Comment by rafaelaroca** [comment]
Hello. Fixed, and took the opportunity to update this page:

https://rafaelaroca.wordpress.com/2021/03/03/block-based-programming-on-raspberry-pi-pico-with-bipes/
