### ISSUE TITLE
The block "Execute Python custom with output" sometimes generate blank lines which prevents running

### ISSUE THREAD

**Issue by mobluse** [BIPES/BIPES#74]
I have a function that uses "Execute Python custom with output", but the generated code has a blank line which makes the automatic pasting of the code to the REPL not work. The REPL at Snek 1.7 on Arduino UNO R3 think that the code has ended at the break.

The generated code from the function CSI() at https://bipes.net.br/ide/#qh4chf
```
def CSI():
  global x, y, string, to, s, csi, m, i, j
  csi = chr(27)

  csi = str(csi) + '['
  return csi
```

**Comment by JorgeGMarques** [comment]
Fixed with 739bb93
