### ISSUE TITLE
DHT11 Issue on esp32 in new version

### ISSUE THREAD

**Issue by WolfOptics** [BIPES/BIPES#87]
Hi sirs,
 In the new version environment, the I got issue using DHT11 sensor as below.
How can we solve this issue?
![Issue_DH11](https://user-images.githubusercontent.com/95401640/147405317-857605f7-04ac-42d6-85f9-525bcd393791.JPG)

**Comment by rafaelaroca** [comment]
Hello @WolfOptics :-)

This seems to be an issue with the sensor or with the connection. Just tried with an ESP8266 and worked on first try:

![image](https://user-images.githubusercontent.com/31751413/147408707-28c0d128-7401-4697-b618-ecf3a56ed47d.png)

If I disconnect the DATA pin, I get the same error you got: ETIMEDOUT

Hope it helps.

**Comment by rafaelaroca** [comment]
Just tried with an ESP32 and it also worked nice! :-)

![image](https://user-images.githubusercontent.com/31751413/147408961-1693c0eb-2b30-493c-ba70-260a7b6c50de.png)

So, please, check your sensor and connections.
