### ISSUE TITLE
Cron

### ISSUE THREAD

**Issue by andrewg78** [BIPES/BIPES#96]
When the Websocket server is started from the Linux Cron, the file list can not be retrieved from the device and connection is being closed.
@reboot python /home/pi/SocketServerWebREPL/socketserverWebREPL.py >/home/pi/bipes.log 2>&1

![cron](https://user-images.githubusercontent.com/2042344/148371218-25c56595-10c0-4adf-acc5-a6509099b484.png)

**Comment by andrewg78** [comment]
Workaround:
It looks like  websocket server works (at the moment) as a terminal application only, in order to push it to the background, we can use a screen command, so we can have it autostarted on the boot process:
@reboot screen -dm bash -c "python /home/pi/SocketServerWebREPL/socketserverWebREPL.py"

**Comment by rafaelaroca** [comment]
Hi @andrewg78. For now, I will close this issue, as you proposed a great workaround. As SocketServerWrebREPL needs a valid environment, it really needs to be started from the screen or other tool that provides a complete environment. Anyway, running it from screen seems a great solution for me.
